name: JSONbin (latest)

on: push

jobs:
  jsonbin:
    name: Test JSONbin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Create bin
        uses: fabasoad/jsonbin-action@v1.0.1
        id: jsonbin_create
        with:
          body: '{"workflow": "${{ github.workflow }}", "author": "${{ github.actor }}", "number": "${{ github.run_number }}"}'
          method: 'CREATE'
          api_key: ${{ secrets.API_KEY }}
      - name: Print bin_id
        run: echo "Bin ID = ${{ steps.jsonbin_create.outputs.bin_id }}"
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@v1.1.0
        id: http1
        with:
          url: '${{ steps.jsonbin_create.outputs.url }}'
          method: 'GET'
          customHeaders: '{"secret-key": "${{ secrets.API_KEY }}"}'
      - name: Print response
        run: printf '${{ steps.http1.outputs.response }}'
      - name: Update bin
        uses: fabasoad/jsonbin-action@v1.0.1
        id: jsonbin_update
        with:
          body: '{"workflow": "${{ github.workflow }}-updated", "author": "${{ github.actor }}-updated", "number": "${{ github.run_number }}-updated"}'
          method: 'UPDATE'
          bin_id: '${{ steps.jsonbin_create.outputs.bin_id }}'
          api_key: ${{ secrets.API_KEY }}
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@v1.1.0
        id: http2
        with:
          url: '${{ steps.jsonbin_update.outputs.url }}'
          method: 'GET'
          customHeaders: '{"secret-key": "${{ secrets.API_KEY }}"}'
      - name: Print response
        run: printf '${{ steps.http2.outputs.response }}'
      - name: Delete bin
        uses: fabasoad/jsonbin-action@v1.0.1
        id: jsonbin_delete
        with:
          bin_id: '${{ steps.jsonbin_update.outputs.bin_id }}'
          method: 'DELETE'
          api_key: ${{ secrets.API_KEY }}
